base_url = "https://thoughtexpo.com"
title = "thoughtexpo"
description = "... leelavg's corner on the internet ..."
compile_sass = true
author = "Leela Venkaiah G"

taxonomies = [
  {name = "tags"},
]

[markdown]
render_emoji = true

[markdown.highlighting]
style = "inline"
light_theme = "zed-onelight"
dark_theme = "blog-gruvbox-dark-soft"
extra_themes = ["themes/zed-onelight.json", "themes/gruvbox-dark-soft.json"]

[extra]
links = [
  {name = "home", url = "@/_index.md"},
  {name = "posts", url = "@/posts/_index.md"},
]
goat_counter = "leelavg"
