on: push
name: build and deploy blog
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache zola
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('.zola_version') }}
          path:
            ./bin/zola-*
      - name: build
        run: |
          make build
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
      - name: deploy
        uses: actions/deploy-pages@v4
